### ISSUE TITLE
Wrong memory/cpu settings shown in the UI

### ISSUE THREAD

**Issue by kkapelon** [okteto/cloud-feedback#22]
I have created two okteto deployments. A go application with the default resources/requests and a Java one with the following:

```
name: spring-boot-2-sample-app
image: okteto/maven:latest
command:
- bash
workdir: /okteto
volumes:
- /root/.m2
forward:
- 8080:8080
- 8088:8088
resources:
  requests:
    memory: "3Gi"
    cpu: "1000m"
  limits:
    memory: "4Gi"
    cpu: "2000m"
```

Whie the total memory used seems to be correct in the UI, the individual resources for each deployment are wrong. They are 1GB, 0,5 cpu regardles of the settings in okteto.yaml

![wrong-memory](https://user-images.githubusercontent.com/214914/71326575-69e68280-2505-11ea-8bbd-b9ddcd171363.png)
