### ISSUE TITLE
Destroying stateful-set does not work

### ISSUE THREAD

**Issue by shyim** [okteto/cloud-feedback#29]
Request
```json
{"query":"mutation DestroyResource($name: String!, $spaceId: String!) {\n      destroyStatefulSet(name: $name, space: $spaceId) {\n        id, name\n      }\n    }","variables":{"name":"es-cluster","spaceId":"shyim"}}
```

Response:

```json
{
	"data": {
		"destroyStatefulSet": null
	},
	"errors": [
		{
			"message": "failed to destroy statefulset",
			"locations": [
				{
					"line": 2,
					"column": 7
				}
			],
			"path": [
				"destroyStatefulSet"
			]
		}
	]
}
```

**Comment by pchico83** [comment]
@shyim was it a temporal issue? was the statefulset finally deleted?
I have been trying to repro the issue with no success. Our logs say your request failed with a `not found` error.

**Comment by shyim** [comment]
Apply this k8s manifest
```
apiVersion: v1
kind: Service
metadata:
    name: elasticsearch-cluster
spec:
    clusterIP: None
    selector:
        app: es-cluster
    ports:
        - name: transport
          port: 9300
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: es-config
data:
    elasticsearch.yml: |
        cluster.name: my-elastic-cluster
        network.host: "0.0.0.0"
        bootstrap.memory_lock: false
        discovery.zen.ping.unicast.hosts: elasticsearch-cluster
        discovery.zen.minimum_master_nodes: 1
        xpack.security.enabled: false
        xpack.monitoring.enabled: false
    ES_JAVA_OPTS: -Xms512m -Xmx512m
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
    name: esnode
spec:
    serviceName: elasticsearch
    replicas: 2
    updateStrategy:
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: es-cluster
        spec:
            securityContext:
                fsGroup: 1000
            containers:
                - name: elasticsearch
                  resources:
                      requests:
                          memory: 1Gi
                  image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
                  env:
                      - name: ES_JAVA_OPTS
                        valueFrom:
                            configMapKeyRef:
                                name: es-config
                                key: ES_JAVA_OPTS
                  readinessProbe:
                      httpGet:
                          scheme: HTTP
                          path: /_cluster/health?local=true
                          port: 9200
                      initialDelaySeconds: 5
                  ports:
                      - containerPort: 9200
                        name: es-http
                      - containerPort: 9300
                        name: es-transport
                  volumeMounts:
                      - name: es-data
                        mountPath: /usr/share/elasticsearch/data
                      - name: elasticsearch-config
                        mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
                        subPath: elasticsearch.yml
            volumes:
                - name: elasticsearch-config
                  configMap:
                      name: es-config
                      items:
                          - key: elasticsearch.yml
                            path: elasticsearch.yml
    volumeClaimTemplates:
        - metadata:
              name: es-data
          spec:
              accessModes: [ "ReadWriteOnce" ]
              resources:
                  requests:
                      storage: 5Gi
```

Try to delete it using okteto cloud ui. It does not work 😢
