### ISSUE TITLE
Secrets should be usable in okteto-stack.yml

### ISSUE THREAD

**Issue by austinrivas** [okteto/cloud-feedback#47]
This is a feature request to support the following use case.

Given an oketeto secret

`SOME_SECRET=supersecret`

It should be usable in `okteto-stack.yml`

```yaml
name: postgres-hasura
services:
  postgres:
    image: postgres:12
    ports:
      - 5432
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${SOME_SECRET}
    resources:
      cpu: 250m
      memory: 0.5Gi
```

This will allow for secrets to be used by multiple services without re declaring the secret in okteto.

For example the following service could consume `SOME_SECRET`

```yaml
graphql-engine:
    public: true
    image: hasura/graphql-engine:v1.2.2
    ports:
      - 8080
    environment:
      - HASURA_GRAPHQL_ADMIN_SECRET=${SOME_SECRET}
      - HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:${SOME_SECRET}@postgres:5432/postgres
      - HASURA_GRAPHQL_ENABLE_CONSOLE='true'
      - HASURA_GRAPHQL_ENABLED_LOG_TYPES='startup, http-log, webhook-log, websocket-log, query-log'
      - 'HASURA_GRAPHQL_JWT_SECRET="{\"type\": \"RS256\", \"jwk_url\": \"http://hasura-backend-plus:3000/auth/jwks\"}"'
    resources:
      cpu: 250m
      memory: 0.5Gi
```

As a reproduction test case you can use the following `okteto-stack` and oketeto secrets

```bash
POSTGRES_PASSWORD=postgrespassword
HASURA_GRAPHQL_ADMIN_SECRET=hasurapassword
S3_BUCKET=hasura-backend-plus
S3_ACCESS_KEY_ID=minio
S3_SECRET_ACCESS_KEY=miniopassword
```

```yaml
name: postgres-hasura
services:
  postgres:
    image: postgres:12
    ports:
      - 5432
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    resources:
      cpu: 250m
      memory: 0.5Gi
  graphql-engine:
    public: true
    image: hasura/graphql-engine:v1.2.2
    ports:
      - 8080
    environment:
      - HASURA_GRAPHQL_ADMIN_SECRET=${HASURA_GRAPHQL_ADMIN_SECRET}
      - HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
      - HASURA_GRAPHQL_ENABLE_CONSOLE='true'
      - HASURA_GRAPHQL_ENABLED_LOG_TYPES='startup, http-log, webhook-log, websocket-log, query-log'
      - 'HASURA_GRAPHQL_JWT_SECRET="{\"type\": \"RS256\", \"jwk_url\": \"http://hasura-backend-plus:3000/auth/jwks\"}"'
    resources:
      cpu: 250m
      memory: 0.5Gi
  hasura-backend-plus:
    public: true
    image: nhost/hasura-backend-plus:latest
    ports:
      - 3000
    environment:
      - AUTO_MIGRATE='true'
      - HASURA_GRAPHQL_ADMIN_SECRET=${HASURA_GRAPHQL_ADMIN_SECRET}
      - HASURA_ENDPOINT=http://graphql-engine:8080/v1/graphql
      - JWT_ALGORITHM=RS256
      - S3_ENDPOINT=http://minio:9000
      - S3_BUCKET=${S3_BUCKET}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
    resources:
      cpu: 250m
      memory: 1Gi
  minio:
    image: minio/minio
    volumes:
      - /data
    environment:
      - S3_BUCKET=${S3_BUCKET}
      - MINIO_ACCESS_KEY=${S3_ACCESS_KEY_ID}
      - MINIO_SECRET_KEY=${S3_SECRET_ACCESS_KEY}
    command: "mkdir -p /export/${S3_BUCKET} && /usr/bin/minio server /export"
    resources:
      cpu: 250m
      memory: 0.5Gi
```
