### ISSUE TITLE
Use a "." instead of a "-" to separate the ingress from the namespace for generated host names

### ISSUE THREAD

**Issue by CtrlZvi** [okteto/cloud-feedback#86]
Currently, for [generated hostnames](https://www.okteto.com/docs/cloud/ssl/#let-okteto-generate-the-host) on ingresses, the hostname is generated by combining the name of the `Ingress` and the name of the `Namespace` with a "-". This means that the combined length of the namespace name AND the ingress name has to be less than 62 characters (63 for a DNS label minus one for the combining "-"). This is a pretty low limit for two names, and can be easily exhausted. By separating the namespace and the ingress with a "." instead, each can be an RFC 1035 label.

This would mean that the wildcard cert currently used for SSL on generated hosts would no longer work, but it's already possible to break that cert by creating an ingress with a "." in the name. It should be possible to use Let's Encrypt to generate a free certificate on demand matching the final generated host instead of a wildcard cert.

To reproduce the issue, try applying the following Kubernetes spec to an Okteto Cloud namespace:
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  selector:
    app.kubernetes.io/name: test
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: abcdefghijklmnopqrstuvwxyz1234567890-zyxwvutsrqponmlkjihgfedcba
  annotations:
    dev.okteto.com/generate-host: "true"
spec:
  rules:
    - host: test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test
                port:
                  name: http
```

The apply will succeed, and everything will "work" fine, including the Okteto web UI showing a link to the deployment, but the DNS name generrated is invalid and DNS resolvers will fail to perform the DNS lookup, making navigation impossible.
