### ISSUE TITLE
`okteto up --detach` ignores `okteto.yml`

### ISSUE THREAD

**Issue by elferia** [okteto/cloud-feedback#90]
docker-compose.yaml

```yaml
services:
  rust-test:
    image: scratch
```

`okteto.yml`

```yaml
dev:
  rust-test:
    image: rust:1-bullseye
```

When I run `okteto up`, `rust-test` k8s deployment will be created and `sh` will be executed on it.
`rust-test` deployment's image is `rust:1-bullseye`.

But when I run `okteto up --detach`, unknown `okteto-dev-env` deployment will be created. Its image is `busybox`.
(And the command will hang up)
`okteto up --detach -f okteto.yml` makes no sense.

OS: Windows 10
